### ISSUE TITLE
为什么CPU占用率这么高？

### ISSUE THREAD

**Issue by yaoshining** [nuysoft/Mock#101]
mac系统，在使用Mock.js之前运行应用CPU温度在55°C左右，用了Mock之后，温度飙升至100°C。

**Comment by nuysoft** [comment]
请提供下数据模板，是否有大数据生成、循环引用？

**Comment by yaoshining** [comment]
本来是想在项目中使用Mock.js进行接口测试，可是在定义完这个代码之后，浏览器打开可以执行并在控制台输出接口，这时候CPU温度就从50多度一直涨到100度，降不下来，风扇呼呼的响，开始还以为是mac的问题，当我把下面两行注释掉之后温度就慢慢恢复正常。我也感觉特别奇怪，不拦截Ajax请求没问题。





这是mock.data.js文件内容：
'use strict';
Mock.mock('http://a.cn', {
    'list|1000-1500': [{
        'id|+1': 1,
        'name': '@ctitle',
        'details': '@csentence',
        'startTime': '@date',
        'endTime': '@date',
        'progress': '@natural(0, 100)'
    }]
});

$(function() {
    $.ajax({
        url: 'http://a.cn',
        success: function(data) {
            console.log(data);
        }
    });
});

**Comment by nuysoft** [comment]
吐槽下代码格式！！！
要生成 1000 - 1500 条，看起来是期望生成的数据量太大的原因。
PS：不明白什么样的场景会需要这种数据？

**Comment by yaoshining** [comment]
是这样的，跟数据量没关系，结构是这样的，开始只是生成几十条，后来这不不能用么，才用代码生成数据，拷贝到json文件里用。而且我不明白即使生成1000多条数据，对于现在的计算能力，也不能算大吧，关键是数据可以瞬间生成，可是cpu温度却一直减不下来，不明白为什么在生成数据之后，还要占用cpu，还要运算什么吗？
