### ISSUE TITLE
现在针对img src的请求无法过滤？

### ISSUE THREAD

**Issue by MingXingTeam** [nuysoft/Mock#102]
我测试了一下 貌似img的src请求是过滤不了的？
像这样的：

``` html
<img src="/code/getRandomCode.do" alt="">
```

**Comment by nuysoft** [comment]
不支持。

两个解决方案：
1. 先生成图片地址，再输出到页面上 https://github.com/nuysoft/Mock/wiki/Image
2. 我猜你想要的可能是这个 https://github.com/imsky/holder
