### ISSUE TITLE
使用Mock.mock( rurl, rtype, function( options ) )方式拦截请求后return中无法使用数据模板和占位符

### ISSUE THREAD

**Issue by sd393268240** [nuysoft/Mock#106]
在回调函数中无法使用数据模板的语法去随机模拟数据，是我的写法问题还是此三方库没有提供回调函数中使用数据模板的功能呢。

`Mock.mock(/message\/multi-image-text\/page/, 'get', function(data){
    var params=getParams(data);
    var newData=
    {
        "data":{
            'string|1-10': "★"

```
    },
    "meta":{}
};
return newData;
```

});`

**Comment by sd393268240** [comment]
暂时找到临时解决办法，就是在Mock.mock的回调中嵌套一个Mock.mock，在子mock里使用数据模板语法生成随机数据，然后通过子mock的返回对象取值放入return对象中。

**Comment by nuysoft** [comment]
你的解决办法是正确的。
通常，第三个参数直接放**数据模板**。
如果要自定义返回数据，才用**回调函数**，此时需要在回调函数中自行调用 `Mock.mock`。
