### ISSUE TITLE
可以生成JSON数组吗？

### ISSUE THREAD

**Issue by yinjun1991** [nuysoft/Mock#120]
怎么使用Mock() 生成JSON数组呢？
例如：
`[
{"name":"小明","age":10},
{"name":"小红","age":11}
]`

**Comment by nuysoft** [comment]
``` js
Mock.mock({
    'list|2': [{
        name: '@cname',
        age: '@int(1,100)'
    }]
}).list
```

**Comment by ww1129** [comment]
你好，Mock.mock({
    'list|2': [{
        name: '@cname',
        age: '@int(1,100)'
    }]
}).list  中@cname  @int(1,100)是什么呀

**Comment by nuysoft** [comment]
@tianwenwen https://github.com/nuysoft/Mock/wiki/Syntax-Specification#%E6%95%B0%E6%8D%AE%E5%8D%A0%E4%BD%8D%E7%AC%A6%E5%AE%9A%E4%B9%89%E8%A7%84%E8%8C%83-dpd

**Comment by ww1129** [comment]
//    "classes|1-10": [{
        //        "classesName": mock.Random.cword(2,4),
        //        "classesId": mock.Random.id()
        //
        //
        //    }] 是这个意思吗
----- 原始邮件 -----
发件人：高云 notifications@github.com
收件人：nuysoft/Mock Mock@noreply.github.com
抄送人：tianwenwen tianwenwen555@sina.com,  Mention mention@noreply.github.com
主题：Re:_[nuysoft/Mock]_可以生成JSON数组吗？_(#120)
日期：2016年07月18日 13点55分

Closed #120.

&mdash;
