### ISSUE TITLE
简单的array

### ISSUE THREAD

**Issue by deded007** [nuysoft/Mock#124]
我想要单纯的array，如下：
`　[ "Mock.js",    "Mock.js",    "Mock.js",    "Mock.js",    "Mock.js",    "Mock.js"  ]`
但是例子中`Mock.mock({
  "array|1-10": [
    "Mock.js"
  ]
})`会得到
`{
[ "Mock.js",    "Mock.js",    "Mock.js",    "Mock.js",    "Mock.js",    "Mock.js"  ]
}`，外面多了{}，要如何正确使用？？

**Comment by any86** [comment]
输出的时候json.array不就ok了

**Comment by TechQuery** [comment]
@383514580 LZ 输出的格式都不对吧？JSON 会解析出错的……

**Comment by any86** [comment]
@TechQuery  我估计他是笔误，他实际代码应该没写错
