### ISSUE TITLE
xhr.addEventListener is not a function(…)

### ISSUE THREAD

**Issue by MillerRen** [nuysoft/Mock#127]
`vue` `vue-resource` `webpack` 文件上传提示 `xhr.addEventListener is not a function(…)`,好像是这个方法被重命名成了 `xhr.addEventListene`即少了个`r`

**Comment by MillerRen** [comment]
#105 重复

**Comment by geetwo** [comment]
Hey this is not a repeat of issue #105 i guess. 
`xhr.addEventListener` works fine but `xhr.upload.addEventLister ` doesnt work therefore i am not able to geat file upload progress event not even when using` xhr.upload.onprogress`.

Please Help with this

**Comment by Telanx** [comment]
@geetwo just add the code below to the file `node_modules/mockjs/dist/mock.js` at line `8308`
```js
MockXMLHttpRequest.prototype.upload = xhr.upload;
```

**Comment by nooldey** [comment]
@Telanx  the better way is to change the file `node_modules/mockjs/src/xhr/xhr.js` at line 216
（更建议的做法是在以上路径文件的第216行，添加如下代码：）

`MockXMLHttpRequest.prototype.upload = xhr.upload;`

确保在生产模式下打包出来的代码正常使用。

**Comment by losymear** [comment]
@nooldey 新版本的mockjs需要加到哪一行呢

**Comment by waketzheng** [comment]
@losymear 一样的放在216行就好.  我的mockjs版本是1.0.1-beta3
然后还要删除 `node_modules/mockjs/dist/` ,  并重新`npm run dev`

- 另外, 直接删除mockjs包和对它的引用, 也是能解决问题的

**Comment by greper** [comment]
我fork修复了这个问题
将原有的mockjs从packag.json中删除
然后执行 npm i mockjs-x --save 即可
