### ISSUE TITLE
不支持jsonp方式?

### ISSUE THREAD

**Issue by yyman001** [nuysoft/Mock#181]
http://xxxx.com/activity/action.php?act=getServerList
类似这种好像没效果,一定要用返回文件的方式吗?
原是`jsonp`方式,
换成`json`方式就成功了,但不支持`jsonp`方式吗?

**Comment by chinesedfan** [comment]
可以试试[parrot-mocker-web](https://github.com/chinesedfan/parrot-mocker-web)，支持xhr/jsonp/fetch
