### ISSUE TITLE
如何在response的header塞入数据

### ISSUE THREAD

**Issue by mingliao** [nuysoft/Mock#187]
mockjs如何在返回的数据头部header塞入数据？有相关的处理方式么？有时候需要做权限认证，需要在头部塞入相关数据。

**Comment by wendux** [comment]
在导入mock后引入（[Ajax-hook](https://github.com/wendux/Ajax-hook)），ajax-hook支持拦截getResponseHeader/getAllResponseHeaders方法，可以在里面修改返回头（这里拦截的是mock xhr的返回）

**Comment by mingliao** [comment]
@wendux  谢啦。哈哈
