### ISSUE TITLE
前端setInterval 隔几秒用ajax请求一次数据，请求到的是一样的数据

### ISSUE THREAD

**Issue by HuangZhenyang** [nuysoft/Mock#199]
您好！我有个业务需求，需要每隔几秒向服务器请求数据。我在用mock.js的Mock.mock()拦截请求、生成随机数时，前端每次收到的数据都是一样的。请问这是为什么呢？应该怎么解决呢？  谢谢！

![default](https://cloud.githubusercontent.com/assets/17945092/26686912/00704f12-4721-11e7-886c-10b31d992260.png)

**Comment by fr0m** [comment]
请把mock部分的代码也放出来吧，看请求也看不出所以然。
如果需要数据一直变化，应该用function的方式去调用并在fucntion内部生成data。

**Comment by HuangZhenyang** [comment]
呃= =   代码是这个：
![qq 20171201114003](https://user-images.githubusercontent.com/17945092/33467004-8c6af846-d68c-11e7-9934-89be73f298cc.png)

"在api方法内部调用"  是在什么api方法呢？  是mockjs的代码还是我发送请求的代码？不是很懂。
  谢谢你的回答！！

**Comment by fr0m** [comment]
sry, 我用的是roadhog集成的mock，跟直接用mock还有点区别，之前没有注意到。
你这个mock代码的问题是没有用mock的template，请参看官方文档：
https://github.com/nuysoft/Mock/wiki/Getting-Started
把data换成mock template传入就可以达到你想要的效果了。

**Comment by HuangZhenyang** [comment]
喔！  好的！  谢谢你！！！ very nice!
