### ISSUE TITLE
RAP学习中心的学习视频都不能看了，请解决一下

### ISSUE THREAD

**Issue by andli0626** [nuysoft/Mock#201]
RAP学习中心的学习视频都不能看了，请解决一下

**Comment by BladeCode** [comment]
发现，可以通过开启浏览器的flash支持，可以查看到视频。
开启方式，可参考以下`任意一种`方法
1. [Adobe Flash 无法正常使用](https://helpx.adobe.com/cn/flash-player/kb/enabling-flash-player-chrome.html)
2. [启用 Adobe Flash Player](https://helpx.adobe.com/cn/flash-player/kb/enabling-flash-player-chrome.html)

非常感谢RAP项目，如有冒犯，请联系我删除视频
如果你嫌烦，我已经将全部视频上传到优酷[《RAP学习中心》](http://v.youku.com/v_show/id_XMjgzODI3MDEzMg==.html?spm=a2h1n.8251843.0.0&f=50157447)
同时如果你觉得不够清晰，我已经将视频上传到[百度网盘](http://pan.baidu.com/s/1i4PR49J)

**Comment by andli0626** [comment]
感谢解答
