### ISSUE TITLE
Mock当前版本不支持Fetch吗？

### ISSUE THREAD

**Issue by qhanw** [nuysoft/Mock#205]
目前在react项目中使用mock，参照官方示例，并未达到拦截的效果，是因为不支持fetch吗，还是说在react中需要特别的配置，可否给出react的示列，或者明确说明是否支持fetch？

**Comment by chinesedfan** [comment]
Duplicate of #163

**Comment by zjffun** [comment]
貌似作者已经不维护了，下面是一个支持拦截 `fetch` 的版本 [zjffun/Mock-support-intercept-fetch](https://github.com/zjffun/Mock-support-intercept-fetch)

使用的话：

```bash
npm install @zjffun/mockjs
```

`fetch` 的拦截还是比较好实现的，因为拦截后返回 resolve 为 response 对象（通过 [Response - Web APIs | MDN](https://developer.mozilla.org/en-US/docs/Web/API/Response) 创建）的 promise 对象就行。
