### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by nuysoft** [nuysoft/Mock#3]
1. √ Handlebars vs XTemplate，测试、语法
2. √ 占位符：支持转义 `@`
3. 50% 在测试用例增加期望的断言个数
4. {{#}} {{^}} 的冲突
5. 嵌套占位符：支持设置参数
6. √ 嵌套占位符：支持为不同路径设置不同的占位符
7. 增加对 URL 中参数 mock 的判断
8. √ 文档：如何扩展占位符

**Comment by wll8** [comment]
请测试使用转义符, 示例:
``` js
Mock.mock('@cname - \\@cname')
```
或尝试使用 mockm 来直接返回数据:
- [如何创建一个自己的接口](https://hongqiye.com/doc/mockm/use/example.html#%E5%A6%82%E4%BD%95%E5%88%9B%E5%BB%BA%E4%B8%80%E4%B8%AA%E8%87%AA%E5%B7%B1%E7%9A%84%E6%8E%A5%E5%8F%A3)
