### ISSUE TITLE
如何跨层级关联数据，求教

### ISSUE THREAD

**Issue by SimoralX** [nuysoft/Mock#302]
![问题描述](https://user-images.githubusercontent.com/30761931/42012262-d9c05834-7ac9-11e8-91a8-db2ea8543645.png)

怎么将数组内的元素和数组外的元素相互关联起来，我知道可以使用 _**function**_
> return this.NeedQuote  // 但那个是同一层级使用的，有没有可以跨层级的？

**Comment by Gebiuncle** [comment]
![image](https://user-images.githubusercontent.com/20454167/43693371-046fe3a6-9960-11e8-9194-2f752094c19e.png)

**Comment by SimoralX** [comment]
@Gebiuncle 谢谢，感谢。
