### ISSUE TITLE
Mock.toJSONSchema( template )

### ISSUE THREAD

**Issue by nuysoft** [nuysoft/Mock#31]
## 规则映射

rule | String | Number | Boolean | Object | Array | Function | RegExp |
---- | ------ | ------ | ------- | ------ | ----- | -------- | ------ |
min  | √      | √      | √       | √      | √     |          | √      |
max  | √      | √      | √       | √      | √     |          | √      |
dmin |        | √      |         |        |       |          |        |
dmax |        | √      |         |        |       |          |        |
step |        | √      |         |        |       |          |        |

**Comment by paolier** [comment]
占位符标签的基础库，已经开发完成尽办。简单举个例子：
如下是是个jsonchema：

```
{
    "title": "custom format attribute demonstration",
    "type": "array",
    "items": {
        "type": "object",
        "properties": {
            "naturalNum": {
                "type": "number",
                "iftest": "@natural(5,10)"
            },
            "isSuccess": {
                "type": "boolean",
                "iftest": "@boolean(5,10)"
            },
            "userMock": {
                "type": "string",
                "iftest": "@mock=sdff"
            }
        }
    }
}
```

下面是data：

```
[
    {
        "naturalNum":456
    },
    {
        "isSuccess":false
    },
    {
        "userMock":"sdff"
    }
]
```

结果是：

```
--- BEGIN MESSAGES ---
error: 超出范围
    level: "error"
    schema: {"loadingURI":"#","pointer":"/items/properties/naturalNum"}
    instance: {"pointer":"/0/naturalNum"}
    domain: "validation"
    keyword: "iftest"
    argumentList: ["5","10"]
    failed: ["456"]
---  END MESSAGES  ---
```

rap这边需要调整的是querySchema接口，对于原本

```
"format":"MOCKJS|A-PART|B-PART"
```

的输出要更改为：

```
"iftest":"B-PART"
```

@Bosn @nuysoft 明天找个15分钟我们电话会议下

**Comment by paolier** [comment]
会议纪要：
1、@Bosn 按照如上修改querySchema接口
2、DEADLINE为：1月23日（周五）完成，包括开发机部署

感谢！么么哒！

**Comment by paolier** [comment]
type：web的情况要扩种一种方法
@url(host,path,query)
例如：要mock 天猫宝贝详情的detail:
     http://detail.tmall.com/item.htm?id=41156775172&spm=a1z09.5.0.0.otr1cg
则为：@url('detail.tmall.com','item.htm','id')
大概是这个意思，不是很严禁，里面的参数可以再细化

@nuysoft 你看呢？

**Comment by paolier** [comment]
我想了下改成这样易用性会更好
@url(example)
@url(example,type)
type=protocal/host/path/query/all，缺省是all
例如：@url('http://detail.tmall.com/item.htm?id=41156775172&spm=a1z09.5.0.0.otr1cg', 'query')
那么仅仅会验证data是url，同时，有两个参数，且为id和spm

**Comment by paolier** [comment]
目前if-validator已经支持了mockjs方法如下：

Type    |	Method
--------  |  ----------
Basics |	boolean, natural, integer, float, character, string
Date	 | date, time, datetime
Image | image
Web	| url
Other | (data)

Other 的example:

```
{
   "type":"string",
   "iftest:"data"
}
```

yes:
```
   "data"
```
no:
```
   "sdf"
```
