### ISSUE TITLE
Mock.Random.dateImage() dont work in nodejs

### ISSUE THREAD

**Issue by DaniloShan** [nuysoft/Mock#34]
```javascript
  app.get('/foo', function (req, res) {
    var data = Mock.mock({
      "thumb": Mock.random.dataImage('200x100', 'test')
    });
    res.jsonp(data);
  });
  // mockjs: v0.1.4
  // nodejs: v0.10.28

**Comment by nuysoft** [comment]
在 node 环境中安装 [canvas](https://github.com/Automattic/node-canvas) 的步骤非常繁琐和容易失败，如果将 canvas 作为 mockjs 的依赖项，可能导致 mockjs 一直安装失败。所以，决定不把 `canvas` 放入 `package.json` 的 `dependencies`。

**不过，一旦你在自己的环境中成功安装了 canvas 包，就可以调用 `Mock.random.dataImage()` 生成 Base64 图片编码。**

https://github.com/nuysoft/Mock/commit/9dd9c7fc45fe545200dc7d8d05f508fbded6eae5#diff-1db2d37ee2d76f5e3865f02a5f79572cR248
