### ISSUE TITLE
Can't get response data's value

### ISSUE THREAD

**Issue by kaisawind** [nuysoft/Mock#352]
The response.data is ok,but response.data.access_token is undefined.
I don't known why, can anyone help me?

![2019-05-07 23-30-00 的屏幕截图](https://user-images.githubusercontent.com/4010613/57312463-32ff6000-7120-11e9-95f9-9d407a3adfed.png)

**Comment by loferatic** [comment]
var access_token = data.data.access_token

**Comment by kaisawind** [comment]
> var access_token = data.data.access_token

Thank you. I have found and modified it.
