### ISSUE TITLE
Mock.js规则控制最外层结构的问题

### ISSUE THREAD

**Issue by Bosn** [nuysoft/Mock#37]
#### 客户描述
新版本提供了两种类型的返回格式：对象、数组。
对于数组，希望返回的是一个数组对象，且能够让mock生成多个项。
但是设定了返回类型为数组，且设定了响应参数后，生成的数据（数组对象），长度一直是1。
是否有什么方式可以让其随机生成不同长度的数组对象？

#### 个人分析
最外层比较特殊，这一块儿请@墨智 老师看看把，上次我们聊到virtual root类似的实现是否可以解决最外层MOCK规则控制的问题呢？

就目前而言，Mock.js并没有对最外层数据提供控制的方式。

**Comment by nuysoft** [comment]
暂不支持。
