### ISSUE TITLE
能不能增加模拟ajax请求延时响应？

### ISSUE THREAD

**Issue by luozhihua** [nuysoft/Mock#39]
有很多ajax请求都是需要有一些界面的交互过程的，比如显示loading提示等，但是现在是没有任何延迟，以至于前期开发过程根本就看不到这些效果，很难调试。

我在我的fork库里面做了些修改，这样调用ajax的响应方法时，就可以延迟几秒，可以更好的模拟真实的网络环境，秒数是一个范围内的随机数：
https://github.com/luozhihua/Mock/blob/master/src/mockjax.js#L52

**Comment by humorHan** [comment]
@nuysoft  不能以请求作为延时配置的最小粒度？因为页面中某些请求可能本身就很耗时...
尝试了async 结果并不支持  建议支持下或者修改为请求的最小粒度
