### ISSUE TITLE
服务端渲染中无法拦截ajax请求

### ISSUE THREAD

**Issue by JinLuhuan** [nuysoft/Mock#411]
服务端渲染中发送的请求都没有拦截啊  
例如nuxt中的asyncData

**Comment by lavyun** [comment]
只支持浏览器端ajax拦截

**Comment by JinLuhuan** [comment]
@lavyun 那服务端渲染的项目有对应的处理方式吗

**Comment by lavyun** [comment]
服务端可以使用 Mock.Random.xxx 和Mock.mock(template)  生成随机数据，但是不支持拦截http请求。

**Comment by JinLuhuan** [comment]
**提供一个解决方案**
在服务端ajax拦截器中补充：
`    config => {`
&nbsp;&nbsp;`      if(isMock && process.server) {  // mock环境下`
&nbsp;&nbsp;&nbsp;&nbsp;`        config.mock = {  // 记录请求内容`
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`          method: config.method,`
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`          url: config.url,`
&nbsp;&nbsp;&nbsp;&nbsp;`        }`
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`// 改成一个万能地址,让请求可以完成`
&nbsp;&nbsp;&nbsp;&nbsp;`        config.method = 'OPTIONS';`
&nbsp;&nbsp;&nbsp;&nbsp;`        config.url = '/uc/auth/access/signIn';`
&nbsp;&nbsp;&nbsp;&nbsp;`        return config`
&nbsp;&nbsp;`     }`
`}`

对应处理response：
` response => {`
&nbsp;&nbsp;`      if(isMock && process.server) {  // mock环境下`
&nbsp;&nbsp;&nbsp;&nbsp;`        const config = { ...response.config.mock };`
&nbsp;&nbsp;&nbsp;&nbsp;`        for(let mock of mockList) {`
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`// 找到对应的mock模版生成后返回即可`
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`          if(config.method.toUpperCase() == mock.method.toUpperCase()) {`
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`            if(mock.url.test(config.url)) {`
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`              return Mock.mock(mock.template)`
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`            }`
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`          }`
&nbsp;&nbsp;&nbsp;&nbsp;`        }`
&nbsp;&nbsp;`      }`
`}`
以上就可以实现ssr服务端拦截了

**Comment by wll8** [comment]
@JinLuhuan

有现成的工具 [mockm](https://hongqiye.com/doc/mockm/?from=ad) 可以方便的实现拦截和记录查看功能，例如：

``` js
{
  "get /my/api": {name: `@cname`}
}
```

这样即可实现一个可以在浏览器上访问的 api.
