### ISSUE TITLE
是不是相同的url返回的数据,都是相同的呢

### ISSUE THREAD

**Issue by qiangspecial** [nuysoft/Mock#42]
Mock.mock(/\/inc\/Task_edit\.htm\?id=/, {
	id: "",
	name: Random.string("upper", 20),
	subName: Random.string("upper", 20),
	userRange: Random.natural(0, 1),
	status: Random.natural(0, 1),
	description: Random.string("upper", 50),
	url: "",
	finish: 0,
	award: 0,
	pic: "",
	showBtn: Random.natural(0, 1),
	activeBtnName: "签到",
	finishBtnName: "已签到",
	orderNo: "1",
	recommend: Random.natural(0, 1),
	platCodes: Random.range(1, 7)
});

这样写,我每次拿到的数据都是一样的,没有变

**Comment by nuysoft** [comment]
@qiangspecial 的数据模板（即 `Mock.mock()` 的第二个参数）已经是固定的数据，所以每次返回的数据都是一样的。

仅以属性 `name` 为例：

```js
Mock.mock(/\/inc\/Task_edit.htm\?id=/, {
    name: '@STRING("upper", 20)'
})
```
