### ISSUE TITLE
Emoji placeholder support in string template?

### ISSUE THREAD

**Issue by lmxx1234567** [nuysoft/Mock#445]
Is it possible to support emoji placeholders like
```json
{
    "emoji":"@emoji()"
}
```

**Comment by wll8** [comment]
You can try a custom method or use a fork of the project: 

- Mock.Random.extend
- @lavyun's work [better-mock](https://github.com/lavyun/better-mock)
- [random-emoji](http://lavyun.gitee.io/better-mock/document/random/text.html#random-emoji)

``` js
Mock.mock(`@emoji`)
```

**Comment by lmxx1234567** [comment]
@wll8 Thanks for your prompt reply. I will try it out. By the way, is MockJS still being maintained?

**Comment by wll8** [comment]
@lmxx1234567 

It seems not. The last update was almost 2 years ago.

But it is a useful tool, so if you encounter a problem, someone will provide a solution.

Many people have created a lot of good tools based on it, such as `yapi` `foxapi`. I am also creating my own [mockm](https://github.com/wll8/mockm), which is based on `better-mock`.
