### ISSUE TITLE
Unreachable 'if' after 'break'

### ISSUE THREAD

**Issue by CatTail** [nuysoft/Mock#50]
See [mock.js](https://github.com/nuysoft/Mock/blame/master/src/mock.js#L308).

Please check your source code with tools like [jshint](https://github.com/jshint/jshint).

And, I hate the code style without semicolon

**Comment by nimojs** [comment]
https://github.com/nuysoft/Mock/blob/master/dist/mock.js dist之后都是有分号
你没发现 mock 的代码风格就是无分号么？https://github.com/nuysoft/Mock/blob/master/src/util.js

**Comment by CatTail** [comment]
This issue is about `Unreachable 'if' after 'break'`. Please see https://github.com/nuysoft/Mock/blame/master/src/mock.js#L308

**Comment by nuysoft** [comment]
thx
