### ISSUE TITLE
如何继续发送ajax请求

### ISSUE THREAD

**Issue by daddybh** [nuysoft/Mock#55]
mockjs很好用，大赞！

使用过程，遇到以下场景，需根据头部决定是否拦截请求

因为接口与前端并行开发，某些接口完成后，不再需要mock data，直接发送请求。

请问mockjs是否支持该场景？应该怎么实现？

```
  Mock.mock(/index\.html/, function(options){
        var headers = options.headers, moduleName = headers["Module"];
        if(moduleName === "mainRecommend"){
            return mockMainRecommend();
        }else if (moduleName === "mainTop"){
            return mockMainList();
        }else{
            //继续发送ajax请求
        }
}
```

**Comment by nimojs** [comment]
你要的是不是这个？
[阿里妈妈的实践](http://mockjs.com/doc/lanlan.html#33)
根据 URL 中是否含有参数 mock 动态加载数据模板

```javascript
// http://host:port?mock
var mock = ~location.search.indexOf('mock')
if(mock) KISSY.use('app/models/data')
```

**Comment by daddybh** [comment]
@nimojs  你意思是自己先做判断，再调用Mock.mock是吗？ 

我是想着通过options来判断方便点，因为参数是在headers里面，而不是url，不知道是否有这种方式？

**Comment by nimojs** [comment]
这个我不清楚。 @nuysoft

**Comment by daddybh** [comment]
ping @nuysoft

**Comment by nuysoft** [comment]
目前的 0.1.x 不支持拦截之后继续请求。

依然建议在调试时统一控制是否需要拦截 Ajax 请求，即 @nimojs 贴的『阿里妈妈的实践』，避免硬编码，也方便工程化。

非常赞的需求，考虑在 0.2.x 中实现。
