### ISSUE TITLE
mockjs.com/#chineseName的示例有误

### ISSUE THREAD

**Issue by JavaCS3** [nuysoft/Mock#63]
文档里面的示例是这样子的

    Random.chineseName()
    // => "林则徐"
    Random.chineseName(2)
    // => "马云"

然而`Random.chineseName(count)`的含义是包含几个名，所以`Random.chineseName(2)`返回`马云`不成立。希望有所改进！

**Comment by nuysoft** [comment]
非常感谢 review。
已修正 http://mockjs.com/#chineseName
