### ISSUE TITLE
nodejs里的版本似乎有点混乱

### ISSUE THREAD

**Issue by jinceon** [nuysoft/Mock#64]
https://www.npmjs.com/package/mockjs
写着0.1.4 is the latest of 3 releases
但是`npm install mockjs`后，里面的`mock.js`文件里赫然写着
```js
var Mock = {
        version: "0.1.2",
        _mocked: {}
    };
```

希望修正。并更新版本。npm上目前最新的版本不包含chineseName

**Comment by nimojs** [comment]
同楼主，希望尽快更新 npm 。我现在是直接本地 require('./mock') ，希望能在 package.json 配置

**Comment by nuysoft** [comment]
在 Mock 0.1.x 上关注的时间少疏忽了。
现统一修复和更新至 0.1.10。
