### ISSUE TITLE
mockjs可以像mockjax一样设置响应状态码和响应时间吗

### ISSUE THREAD

**Issue by yeyeye0525** [nuysoft/Mock#65]
$.mockjax({
			url: /get/,
			status: 200,
			responseTime: 750,
                        responseText:'hello world'
})

**Comment by nuysoft** [comment]
不支持。
不过，你可以同时使用  mockjax 和 mockjs，就像这样：

```js
$.mockjax({
    url: /get/,
    status: 200,
    responseTime: 750,
    responseText: Mock.mock({
        whoami: 'hello @name'
    })
})
```
