### ISSUE TITLE
Mock.mock options always undefined.

### ISSUE THREAD

**Issue by PetersonLian** [nuysoft/Mock#66]
I am using zepto instead of jquery.  
  
    Mock.mockjax($);
    Mock.mock(/\gateway.php$/, function(options){
        var url = options.url.trim() || '';
        //options === undefined.Why?
        if(/getLotteryInfo/.test(url)){
        ...
        }  

Then do $.ajax the following way  
    
    $.ajax({
            url:'/gateway.php'
            ,data: args
            ,success: cb
            ,error: ecb
    });  
 
options is always undefined. Any idea?

**Comment by PetersonLian** [comment]
# 问题一，上述的options为undefined  
不装逼了。直接上中文。  
我发现，当用zepto的时候，其实函数都没有传入options。即，mockjax.js的下面代码  

    /*
    for Zepto
    因为 Zepto 并没有实现类似 jQuery.ajaxPrefilter 等预处理函数，所以将和 KISSY 类似直接粗暴处    理。
    */
    if (typeof Zepto != 'undefined') {
    Mock.mockjax = function(Zepto) {
        var __original_ajax = Zepto.ajax
        var xhr = {
            readyState: 4,
            responseText: '',
            responseXML: null,
            state: 2,
            status: 200,
            statusText: 'success',
            timeoutTimer: null
        }

        Zepto.ajax = function(options) {
            var item = find(options)
            if (item) {
                var data = Mock.mock(item.template)
                if (options.success) options.success(data, xhr, options)
                if (options.complete) options.complete(xhr.status, xhr, options)
                return xhr
            }
            return __original_ajax.call(Zepto, options)
        }
      }

      Mock.mockjax(Zepto)
    }  

上述代码中的代码`var data = Mock.mock(item.template)`，由于我用的`item.template`是函数，故而，我改成`var data = Mock.mock(item.template(options))`,这样就有参数传入了。  
故而我认为，你提供的zepto的mockjax的实现，是否漏考虑了`item.template`是函数的情况。  

# 问题二，依然是mockjax。 zepto.ajaxPrefilter是undefined。会出错。 
mockjax.js下的代码  

    /*
    ### Mock.mockjax(library)
    覆盖（拦截） Ajax 请求，目前内置支持 jQuery、Zepto、KISSY。
    */
    // for jQuery
    Mock.mockjax = function mockjax(jQuery) {
    省略若干字......
    // #22 步加载js文件的时候发现问题
    // #23 Mock.mockjax 导致 $.getScript 不执行回调
    jQuery.ajaxPrefilter('json jsonp script', prefilter)

    return Mock
    }

    if (typeof jQuery != 'undefined') Mock.mockjax(jQuery)
    /*
    for Zepto
    因为 Zepto 并没有实现类似 jQuery.ajaxPrefilter 等预处理函数，所以将和 KISSY 类似直接粗暴处理。
    */
    if (typeof Zepto != 'undefined') {
    省略}

其中`jQuery.ajaxPrefilter('json jsonp script', prefilter)`会出错，因为当用require.js来加载的时候，如果不指定shim依赖(即指定mock依赖于jquery或者zepto之类的)，很有可能mock比zepto(以我实际操作出现的为例)更早加载完成。从而导致，mock.js中的代码`if (typeof Zepto != 'undefined') {`为假的,从而`Mock.mockjax`函数没有被重写（或者称之为覆盖），从而导致，会出现上述代码`jQuery.ajaxPrefilter('json jsonp script', prefilter)`在运行时，其实传入的是Zepto对象。从而此句代码会报错。  
我的workaroud是将该句代码改成    

            if (typeof jQuery.ajaxPrefilter == "function") {
        jQuery.ajaxPrefilter("json jsonp script", prefilter);
        }

**Comment by nuysoft** [comment]
问题 1：[fixed](https://github.com/nuysoft/Mock/commit/f38933fe75aa226e2b791323dfa21a5b497739d9)
问题 2：在应用中配置 shim 或手动调用 [Mock.mockjax(library)](http://mockjs.com/#mockjax)
