### ISSUE TITLE
Mock.setup is not a function

### ISSUE THREAD

**Issue by riskers** [nuysoft/Mock#72]
想用 [Mock.setup](https://github.com/nuysoft/Mock/wiki/Mock.setup()) 设置延迟，但是并没有找到这个方法，我就是这样写的：
```js
Mock.setup({
    timeout: '200-600'
})
```

**Comment by nuysoft** [comment]
方法 `Mock.setup()` 从 0.2.x 开始才会生效。

`bower install mockjs#0.2.0-alpha1` 

或者直接安装 0.2.x 分支

`bower install mockjs#refactoring`

**Comment by chencmgithub** [comment]
我的都是 1.1.0版本了，还是不支持setup，调用Mock.setup，报 Cannot read property 'setup' of undefined

**Comment by anshu1121** [comment]
我的也是1.1.0，也是不支持setup，提示Cannot read property 'setup' of undefined

**Comment by wll8** [comment]
老大说了，0.2.x 才有此功能。

@AnShuKeepRunning  @chencmgithub  也可以试试代理解决方式 [如何延迟接口的响应时间](https://hongqiye.com/doc/mockm/use/example.html#%E5%A6%82%E4%BD%95%E5%BB%B6%E8%BF%9F%E5%90%8E%E7%AB%AF%E6%8E%A5%E5%8F%A3%E7%9A%84%E5%93%8D%E5%BA%94%E6%97%B6%E9%97%B4)
