### ISSUE TITLE
使用mock.js产生404错误

### ISSUE THREAD

**Issue by lmz2423** [nuysoft/Mock#73]
<pre>
$.ajax({
    url: 'hello.json',
    dataType: 'json'
}).done(function(data, status, xhr){
    console.log(
        JSON.stringify(data, null, 4)
    )    
})
</pre>

结果产生404错误，无法拦截XMLHttpRequest请求

**Comment by gimm** [comment]
+1
这么明显的问题，难道是我的用法不对？

**Comment by nuysoft** [comment]
使用的版本是多少？请在 http://jsfiddle.net/ 中提供一下复现场景。
