### ISSUE TITLE
object key 生成

### ISSUE THREAD

**Issue by lonelyclick** [nuysoft/Mock#77]
如果要生成一下数据：

{
  a:{
      name:'a',
      attr:111
     },
b:{
 name:'b',
attr:2222
}
}

a,b要随机，怎么办呢

**Comment by nuysoft** [comment]
格式化下代码好吗？

```
Mock.mock({
    'a_or_b|1': {
        a: {
            name: 'a',
            attr: 111
        },
        b: {
            name: 'b',
            attr: 2222
        }
    }
})['a_or_b']
```

见文档 https://github.com/nuysoft/Mock/wiki/Syntax-Specification#4-%E5%B1%9E%E6%80%A7%E5%80%BC%E6%98%AF%E5%AF%B9%E8%B1%A1-object
