### ISSUE TITLE
如何让datetime累加一定增量

### ISSUE THREAD

**Issue by yelingfeng** [nuysoft/Mock#78]
如题 
想做一套最近10天的时间数据 该如何写？

**Comment by nuysoft** [comment]
使用自定义函数可以实现。

文档 [Wiki](https://github.com/nuysoft/Mock/wiki/Syntax-Specification#6-%E5%B1%9E%E6%80%A7%E5%80%BC%E6%98%AF%E5%87%BD%E6%95%B0-function)

最近10天示例 [JSFiddle](http://jsfiddle.net/bzgamsL7/)
