### ISSUE TITLE
Mock.mock(rurl, rtype, template)

### ISSUE THREAD

**Issue by nuysoft** [nuysoft/Mock#8]
目前 Mock.mock() 支持的方法签名有：
- Mock.mock(template)
- Mock.mock(rurl, template)

@chongzhi 建议增加一个参数 rtype，以区分相同 URL 但是请求类型（GET、POST、PUSH、DELETE等）不同的场景，即支持 RESTFul 风格的 API：
- Mock.mock(rurl, rtype, template)

**Comment by baizn** [comment]
并不起作用啊
