### ISSUE TITLE
什么时候发布1.0？

### ISSUE THREAD

**Issue by nimojs** [nuysoft/Mock#80]
> Random.chineseName() 可以简写为 Random.cname()。从 Mock 0.2 开始，将只保留 Random.cname()。

看过 Graphs， 快速开发的阶段应该是在2013年。现在是 0.1 版本。希升级到 1.0 版本后在 node 中使用 `ˆ1.0.0` 依赖 mockjs

> 如果大版本号为0，则插入号的行为与波浪号相同，这是因为此时处于开发阶段，即使是次要版本号变动，也可能带来程序的不兼容。

> 指定版本：比如1.2.2，遵循“大版本.次要版本.小版本”的格式规定，安装时只安装指定版本。
波浪号（tilde）+指定版本：比如~1.2.2，表示安装1.2.x的最新版本（不低于1.2.2），但是不安装1.3.x，也就是说安装时不改变大版本号和次要版本号。
插入号（caret）+指定版本：比如ˆ1.2.2，表示安装1.x.x的最新版本（不低于1.2.2），但是不安装2.x.x，也就是说安装时不改变大版本号。需要注意的是，**如果大版本号为0，则插入号的行为与波浪号相同，这是因为此时处于开发阶段，即使是次要版本号变动，也可能带来程序的不兼容。**
latest：安装最新版本。

**Comment by nuysoft** [comment]
很赞的建议，谢谢。

发布了 [1.0.0-beta1](https://github.com/nuysoft/Mock/releases/tag/1.0.0-beta1)，网站和文档正在更新中。

**Comment by nuysoft** [comment]
已发布 [1.0.0](https://github.com/nuysoft/Mock/releases/tag/1.0.0) :ok_hand:
