### ISSUE TITLE
Mock.mock(rurl, function(options){return options}) 

### ISSUE THREAD

**Issue by gynsolomon** [nuysoft/Mock#82]
请问新版本是不是将options内容简化为只有url,type两个属性了,为什么呢

**Comment by nuysoft** [comment]
没有啊，你是从哪里看到的？

文档在这里 https://github.com/nuysoft/Mock/wiki/Mock.mock()

**Comment by gynsolomon** [comment]
您点进文档里面function(options)下面的那个jsFiddle，可以看到执行结果是只有url和type这两个属性的

**Comment by nuysoft** [comment]
> 从 1.0 开始，Mock.js 通过覆盖和模拟原生 XMLHttpRequest 的行为来拦截 Ajax 请求，不再依赖于第三方 Ajax 工具库（例如 jQuery、Zepto 等）。

[JSFiddle](http://jsfiddle.net/nuysoft/2s5t5/15/)

在 0.1.x 中，拦截 Ajax 请求的实现依赖于具体的 Ajax 库，必须做针对性的扩展，限制了 Mock.js 的应用场景。

> 在 0.1.x 中，此时，函数 `function(options)` 的参数 `options` 在 jQuery、Zepto、KISSY 的值也不完全一样。

**从 1.0 开始，拦截 Ajax 请求的实现遵循了 [XMLHttpRequest 规范](https://xhr.spec.whatwg.org/)，只包含 `url`、`type` 和 `body`。**

**Comment by gynsolomon** [comment]
@nuysoft 好的, 谢谢您的耐心解答!  :-)
