### ISSUE TITLE
引用dist里面的mock.js在seajs里面提示出错

### ISSUE THREAD

**Issue by web-yuzm** [nuysoft/Mock#83]
```
Mock.mock(/\.json/, {
    'list|1-10': [{
        'id|+1': 1,
        'email': '@EMAIL'
    }]
})
$.ajax({
    url: 'hello.json',
    dataType: 'json'
}).done(function(data, status, jqXHR){
    $('<pre>').text(JSON.stringify(data, null, 4))
        .appendTo('body')
})
```

控制台上出现红色字：Uncaught TypeError: Cannot read property 'mock' of undefined
这事我今天早上刚从这里下载的包

**Comment by nuysoft** [comment]
提 issue 的时候格式化下代码好不好？这是第二条了！！！

**Comment by nuysoft** [comment]
新发布的 [1.0.0-beta1](https://github.com/nuysoft/Mock/releases/tag/1.0.0-beta1) 尚不支持 Sea.js。如果 Sea.js 社区提供了 webpack 插件，才会支持。
如果是在 Sea.js 环境中，请用 [0.1.11](https://github.com/nuysoft/Mock/releases/tag/0.1.11)。
