### ISSUE TITLE
阻止ajax请求的时候，只支持juqey的$.ajax吗？$.post() $.getJSON()等不阻止？

### ISSUE THREAD

**Issue by jiayaoaaa** [nuysoft/Mock#84]
阻止ajax请求的时候，只支持juqey的$.ajax吗？$.post() $.getJSON()等不阻止？

**Comment by nuysoft** [comment]
1. 阻止；
2. 与第三方 Ajax 库无关。

参见 https://github.com/nuysoft/Mock/wiki/Mock.mock()#options

> PS：文档里有相关的说明和 JSFiddle 示例，自己稍微修改下代码就可以验证。
