### ISSUE TITLE
是否支持从 query/post 里面取数据？

### ISSUE THREAD

**Issue by YuhangGe** [nuysoft/Mock#85]
比如 koa 中类似于这样的用法，

``` js
const mock = require('mockjs');
this.body = mock.mock({
  'name': '@CNAME',
  'page': '@query("page")'
}, Object.assign({}, this.request.query, this.request.body));
```

第二个参数用于传递额外的数据，内部通过 @query（也可能是其它名字） 来取。

**Comment by nuysoft** [comment]
不支持。

不过你可以试试 [自定义函数](https://github.com/nuysoft/Mock/wiki/Syntax-Specification#6-%E5%B1%9E%E6%80%A7%E5%80%BC%E6%98%AF%E5%87%BD%E6%95%B0-function)。
