### ISSUE TITLE
数据模板是否可以支持正则

### ISSUE THREAD

**Issue by zhenhua-lee** [nuysoft/Mock#89]
目前开发中，数据mock用到了mockjs的数据模板部分，很好用，非常感谢。

但是数据类型有限，尤其是正则，是否可以使用[randexp](https://www.npmjs.com/package/randexp)类似的模块支持正则。

其他一些想法: 可以借鉴[dreamjs](https://github.com/adleroliveira/dreamjs)，支持schema。

**Comment by nuysoft** [comment]
**问题1：正则**
最近发布的 [1.x](https://github.com/nuysoft/Mock/releases) 已经支持正则。
文档点击这里 => [如果属性值是正则表达式 RegExp，则反向生成可以匹配它的字符串。](https://github.com/nuysoft/Mock/wiki/Syntax-Specification#7-%E5%B1%9E%E6%80%A7%E5%80%BC%E6%98%AF%E6%AD%A3%E5%88%99%E8%A1%A8%E8%BE%BE%E5%BC%8F-regexp)

**问题2：JSON Schema**

提供了方法 [`Mock.toJSONSchema( template )`](https://github.com/nuysoft/Mock/wiki/Mock.toJSONSchema%28%29) 把 Mock.js 风格的数据模板转换成 JSON Schema。

> JSON Schema 的语法是反人类的！
> Mock.js 的语法更便于手工书写，JSON Schema 的语法则对机器解析更友好，所以 Mock.js 会保持现有的语法。
