### ISSUE TITLE
mockjs & angular 中，mock 数据始终返回 null

### ISSUE THREAD

**Issue by qddegtya** [nuysoft/Mock#92]
问题产生的原因是，Angular 中的 xhr.onload 方法中有这样一个判断

``` javascript
// responseText is the old-school way of retrieving response (supported by IE9)
// response/responseType properties were introduced in XHR Level2 spec (supported by IE10)
var response = ('response' in xhr) ? xhr.response : xhr.responseText;
```

由于 mockjs 负责拦截的 done function 中只赋值了 responseText，原型链上的 response 的初始值被设置成了 null，所以('response' in xhr)为 true，导致 Mock 时取到的数据一直为 null.

``` javascript
that.responseText = JSON.stringify(
  convert(that.custom.template, that.custom.options)
  , null
  , 4
)
```

已提 PR

**Comment by qddegtya** [comment]
<p data-height="268" data-theme-id="884" data-slug-hash="wMmOqO" data-default-tab="html" data-user="qddegtya" class='codepen'>See the Pen <a href='http://codepen.io/qddegtya/pen/wMmOqO/'>mockjs & angular</a> by Archer (<a href='http://codepen.io/qddegtya'>@qddegtya</a>) on <a href='http://codepen.io'>CodePen</a>.</p>

<script async src="//assets.codepen.io/assets/embed/ei.js"></script>

**Comment by qmy777** [comment]
@qddegtya @nuysoft 
两位大大，这个问题似乎在mock.js中解决了，但min里面依然返回null
问题如下所示，我用的是requirejs加载的，XHR是用的angular的$http服务
![image](https://user-images.githubusercontent.com/9345799/29251331-8fc4a8fa-8085-11e7-95fe-5eb5729c5d52.png)
![image](https://user-images.githubusercontent.com/9345799/29251337-a5e5cb32-8085-11e7-941b-69c91a8d065d.png)
