### ISSUE TITLE
valid的问题，使用数据占位符后valid判断有误

### ISSUE THREAD

**Issue by pktest1** [nuysoft/Mock#94]
Mock.valid({"email":"@email"}, Mock.mock({"email":"@email"}))

**Comment by pktest1** [comment]
value为正则的时候也有同样的问题
Mock.valid({'regexp': /[a-z][A-Z][0-9]/}, {'regexp': 'yL5'})

**Comment by wjs** [comment]
请作者发一版 1.0.1-beta3 发布到 npm 上，谢谢～
