### ISSUE TITLE
withCredentials 冲突

### ISSUE THREAD

**Issue by speedornothing** [nuysoft/Mock#95]
页面引入 mock.js 后,  jquery ajax 配置 withCredentials = true 是不起作用的, 去掉 mockjs 后 withCredentials 才会起作用. 猜测 mockjs 在劫持底层 xhr 后导致不兼容 withCredentials 

我的使用场景比较特殊, 一部分数据是用 mockjs 模拟, 另一部分数据来自跨域请求

**Comment by janeluck** [comment]
我也是部分mock部分跨域。 看了下源码, 初始化MockXMLHttpRequest时withCredentials的参数写的是false
