### ISSUE TITLE
有没有基于Mock.js的grunt插件，根据配置规则可以直接生成api文档的

### ISSUE THREAD

**Issue by soonyh** [nuysoft/Mock#99]
如题

**Comment by nuysoft** [comment]
没有。

亲可以自己开发一个这样的 grunt 插件，Mock.js 提供了接口 [Mock.toJSONSchema( template )](https://github.com/nuysoft/Mock/wiki/Mock.toJSONSchema%28%29) 来暴露配置的规则，基于这个接口，你可以生成各种格式的文档（Markdown、HTML 等）。

如果开发好了，记得回来记录下，分享给其他小伙伴。

**Comment by bubkoo** [comment]
@soonyh 可以使用 [grunt-restful-mock](https://www.npmjs.com/package/grunt-restful-mock)
